mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('random/', include('random_app.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/random_app/urls.py
from django.urls import path 

from . import views 

urlpatterns = [
    path('', views.test, name="test"),
]

mysite/polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

class Question (models.Model):
    DoesNotExist = models.Manager()
    objects = models.Manager()
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice (models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

mysite/random_app/models.py
from django.db import models

# Create your models here.

class Pergunta (models.Model):
    pergunta_text = models.CharField(max_length=200)
    publicacao_date = models.DateTimeField('date published')

class Escolha (models.Model):
    pergunta = models.ForeignKey(Pergunta, on_delete=models.CASCADE)
    escolha_text = models.CharField(max_length=200)
    votos = models.IntegerField(default=0)

mysite/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from django.template import loader

from .models import Question

# Create your views here.

#def index (request):
#    return HttpResponse ("Hello, world! You're currently at the polls index.")
    
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def results (request, question_id):
    response = "You're currently looking at the results of question %s"
    return HttpResponse(response % question_id)

def vote (request, question_id):
    return HttpResponse ("You're currently voting on question %s" % question_id)

# Useful views that really do things:

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)

mysite/random_app/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def test (request):
    return HttpResponse ("Well, this one looks more like a random app, rather than an index for the polls app, doesn't it?")

mysite/polls/templates/polls/detail.html
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title> Questão "{{ question.question_text }}" </title>
    </head>
    
    <body>
        <h1>{{ question.question_text }}</h1>
        <ul>
            {% for choice in question.choice_set.all %}
                <li>{{ choice.choice_text }}</li>
            {% endfor %}
        </ul>
    </body>
</html>

mysite/polls/templates/polls/index.html
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>So many questions and alternatives...</title>
</head>

<body>
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
    {% else %}
        <p>No polls are available.</p>
{% endif %}
</body>

</html>